#!/bin/bash
# D. Racine 20100609

C=$(stty -a |grep -om1 'columns.*[0-9]\{2,4\}' |sed -e 's/[^0-9]//g')

ones() {
  for ((i=1;i<=$C;i++)); do
    printf "%s" $((i%10)); done; printf "\n"; }

tens() {
  for ((i=1;i<=$((C/10));i++)); do
    printf "%10s" $((i%10)); done; printf "\n"; }

[ "x$1" != "x" ] && { ones; tens; } || { tens; ones; }
